/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v4;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300c0;
        public static final int font = 0x7f0300f3;
        public static final int fontProviderAuthority = 0x7f0300f5;
        public static final int fontProviderCerts = 0x7f0300f6;
        public static final int fontProviderFetchStrategy = 0x7f0300f7;
        public static final int fontProviderFetchTimeout = 0x7f0300f8;
        public static final int fontProviderPackage = 0x7f0300f9;
        public static final int fontProviderQuery = 0x7f0300fa;
        public static final int fontStyle = 0x7f0300fb;
        public static final int fontVariationSettings = 0x7f0300fc;
        public static final int fontWeight = 0x7f0300fd;
        public static final int keylines = 0x7f03012b;
        public static final int layout_anchor = 0x7f030134;
        public static final int layout_anchorGravity = 0x7f030135;
        public static final int layout_behavior = 0x7f030136;
        public static final int layout_dodgeInsetEdges = 0x7f030162;
        public static final int layout_insetEdge = 0x7f03016b;
        public static final int layout_keyline = 0x7f03016c;
        public static final int statusBarBackground = 0x7f0301cb;
        public static final int ttcIndex = 0x7f03022d;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050091;
        public static final int notification_icon_bg_color = 0x7f050092;
        public static final int notification_material_background_media_default_color = 0x7f050093;
        public static final int primary_text_default_material_dark = 0x7f050098;
        public static final int ripple_material_light = 0x7f05009d;
        public static final int secondary_text_default_material_dark = 0x7f05009e;
        public static fi